# Generated by Django 3.1.5 on 2021-04-10 04:23

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cursor', models.ImageField(upload_to=Home.models.uploadCursor)),
            ],
        ),
    ]
