# Generated by Django 3.1.5 on 2021-04-09 14:32

import Portfolio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=1000)),
                ('icon', models.ImageField(upload_to=Portfolio.models.uploadSkillIcon)),
                ('kind', models.CharField(choices=[('skills', 'skills'), ('tools', 'tools')], max_length=80)),
                ('section', models.CharField(choices=[('ProgrammingLanguage', 'ProgrammingLanguage'), ('Framework', 'Framework'), ('Database', 'Database'), ('DevOp', 'ProgrammingLanguage'), ('Library', 'Library')], max_length=100)),
                ('abilites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='Portfolio.use')),
                ('uses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='Portfolio.use')),
            ],
        ),
    ]
