# Generated by Django 3.1.5 on 2021-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='abilites',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='uses',
            field=models.TextField(max_length=1000),
        ),
    ]
