# Generated by Django 3.1.5 on 2021-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20210409_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='yearsOfExprience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='kind',
            field=models.CharField(choices=[('skill', 'skill'), ('tool', 'tool')], max_length=80),
        ),
    ]
