# Generated by Django 3.1.5 on 2021-04-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20210409_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='summary',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
