# Generated by Django 3.1.5 on 2021-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_skill_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='section',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Framework', 'Framework'), ('Database', 'Database'), ('DevOp', 'DevOp'), ('Library', 'Library')], max_length=100),
        ),
    ]
