# Generated by Django 3.1.5 on 2021-04-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_auto_20210409_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='abilites',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='about',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='summary',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='uses',
            field=models.TextField(max_length=10000),
        ),
    ]
