# Generated by Django 3.1.5 on 2021-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_auto_20210409_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='abilites',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='about',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='section',
            field=models.CharField(blank=True, choices=[('Programming Language', 'Programming Language'), ('Framework', 'Framework'), ('Database', 'Database'), ('DevOp', 'DevOp'), ('Library', 'Library')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='summary',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='uses',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='yearsOfExprience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
