# Generated by Django 3.1.5 on 2021-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_auto_20210411_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
