# Generated by Django 4.1.1 on 2022-09-25 16:07

import Portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0012_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Portfolio.models.uploadCertificateImage)),
            ],
        ),
    ]
