# Generated by Django 4.1.1 on 2022-09-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0013_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
