# Generated by Django 4.2.23 on 2025-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0015_certificate_description_certificate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='aspect_ratio',
            field=models.FloatField(blank=True, help_text='Width/Height ratio', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(blank=True, choices=[('courses', 'Courses'), ('contests', 'Contests'), ('benchmarks', 'Benchmarks'), ('participation', 'Participation'), ('scholarships', 'Scholarships')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
