# Generated by Django 4.2.23 on 2025-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0018_alter_socialmedia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab'), ('Bitbucket', 'Bitbucket'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('X', 'X (Twitter)'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('Twitch', 'Twitch'), ('Reddit', 'Reddit'), ('StackOverflow', 'Stack Overflow'), ('Hashnode', 'Hashnode'), ('DevTo', 'Dev.to'), ('Medium', 'Medium'), ('Dribbble', 'Dribbble'), ('Behance', 'Behance'), ('CodePen', 'CodePen'), ('LeetCode', 'LeetCode'), ('HackerRank', 'HackerRank'), ('Codeforces', 'Codeforces'), ('Codewars', 'Codewars'), ('Kaggle', 'Kaggle'), ('Replit', 'Replit'), ('Discord', 'Discord'), ('Telegram', 'Telegram'), ('Figma', 'Figma'), ('ProductHunt', 'Product Hunt'), ('Substack', 'Substack'), ('Notion', 'Notion'), ('Other', 'Other')], max_length=100),
        ),
    ]
