# Generated by Django 4.2.23 on 2025-07-04 02:34

import Portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0019_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platforms', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('scripts', 'Scripts'), ('cli', 'CLI'), ('software_gui', 'Software/GUI')], max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(upload_to=Portfolio.models.uploadWorkImage)),
                ('status', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('stack', models.ManyToManyField(to='Portfolio.skill')),
            ],
        ),
        migrations.DeleteModel(
            name='work',
        ),
    ]
