# Generated by Django 4.2.23 on 2025-07-04 02:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0020_project_delete_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('scripts', 'Scripts'), ('cli', 'CLI'), ('software_gui', 'Software/GUI')], max_length=35),
        ),
    ]
