# Generated by Django 4.2.23 on 2025-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0021_alter_project_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
